proxy:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/nginx_config:/etc/nginx
    - ${NFS_HOST}/nfs/nginx_releasenote:/usr/share/nginx/html

ldap:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/ldap_db:/var/lib/ldap
    - ${NFS_HOST}/nfs/ldap_static:/etc/ldap

